# title: Cayman theme
description: <a href="https://renyurui.github.io">Yurui</a>, Yubo Wu, Thomas H. Li, Shan Liu, <a href="http://www.ece.pku.edu.cn/info/1012/1091.htm">Ge Li</a> <br>  <a href="https://2021.acmmm.org/">ACM MM 2021</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman